name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract build number
      id: build-number
      run: echo "BUILD_NUMBER=${{ github.run_id }}" >> $GITHUB_ENV

    - name: Build and push Docker image with build number tag
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          karimeid1/troubleshooting-container:latest
          karimeid1/troubleshooting-container:${{ env.BUILD_NUMBER }}
      
    - name: Log out from Docker Hub
      run: docker logout
